package inventory

import (
	"crypto/sha1"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type Scanner struct {
	Home     string
	Hostname string
	Now      func() time.Time
}

type pathSpec struct {
	Tool           string
	RelPath        string
	KindHint       string
	Classification Classification
	Risk           RiskLevel
	Reason         string
	Recommendation string
	CheckMCP       bool
}

type adapterSpec struct {
	Name        string
	Description string
	Paths       []pathSpec
}

func NewScanner(home string) Scanner {
	if home == "" {
		home, _ = os.UserHomeDir()
	}
	host, _ := os.Hostname()
	return Scanner{Home: home, Hostname: host, Now: time.Now}
}

func (s Scanner) Scan() Report {
	now := s.now()
	report := Report{
		GeneratedAt: now,
		Hostname:    s.Hostname,
		Home:        s.Home,
		Summary: Summary{
			ByClassification: map[Classification]int{},
			ByRisk:           map[RiskLevel]int{},
			Tools:            map[string]int{},
		},
	}

	for _, adapter := range adapters() {
		status := AdapterStatus{
			Name:        adapter.Name,
			Description: adapter.Description,
		}

		for _, spec := range adapter.Paths {
			path := s.expand(spec.RelPath)
			status.Checked = append(status.Checked, path)
			item, ok := inspectPath(path, spec)
			if !ok {
				continue
			}
			item.ID = stableID(item.Tool, item.Path)
			report.Items = append(report.Items, item)
			status.Available = true
			status.Found = append(status.Found, path)
			report.Findings = append(report.Findings, inspectMCP(item, spec)...)
		}

		sort.Strings(status.Checked)
		sort.Strings(status.Found)
		report.Adapters = append(report.Adapters, status)
	}

	sort.Slice(report.Items, func(i, j int) bool {
		if report.Items[i].Tool == report.Items[j].Tool {
			return report.Items[i].Path < report.Items[j].Path
		}
		return report.Items[i].Tool < report.Items[j].Tool
	})
	sort.Slice(report.Findings, func(i, j int) bool {
		if report.Findings[i].Severity == report.Findings[j].Severity {
			return report.Findings[i].Path < report.Findings[j].Path
		}
		return severityRank(report.Findings[i].Severity) > severityRank(report.Findings[j].Severity)
	})

	report.Summary.TotalItems = len(report.Items)
	report.Summary.TotalFindings = len(report.Findings)
	for _, item := range report.Items {
		report.Summary.ByClassification[item.Classification]++
		report.Summary.ByRisk[item.Risk]++
		report.Summary.Tools[item.Tool]++
	}

	return report
}

func (s Scanner) now() time.Time {
	if s.Now != nil {
		return s.Now().UTC()
	}
	return time.Now().UTC()
}

func (s Scanner) expand(rel string) string {
	if strings.HasPrefix(rel, "~/") {
		return filepath.Join(s.Home, strings.TrimPrefix(rel, "~/"))
	}
	if rel == "~" {
		return s.Home
	}
	return rel
}

func inspectPath(path string, spec pathSpec) (Item, bool) {
	info, err := os.Lstat(path)
	if err != nil {
		return Item{}, false
	}

	kind := spec.KindHint
	switch {
	case info.Mode()&os.ModeSymlink != 0:
		kind = "symlink"
	case info.IsDir():
		kind = "directory"
	case kind == "":
		kind = "file"
	}

	mod := info.ModTime().UTC()
	return Item{
		Tool:           spec.Tool,
		Path:           path,
		Kind:           kind,
		Classification: spec.Classification,
		Risk:           spec.Risk,
		Reason:         spec.Reason,
		Recommendation: spec.Recommendation,
		Exists:         true,
		SizeBytes:      info.Size(),
		ModTime:        &mod,
		Metadata: map[string]string{
			"source": "nightward-adapter",
		},
	}, true
}

func stableID(parts ...string) string {
	hash := sha1.Sum([]byte(strings.Join(parts, "\x00")))
	return hex.EncodeToString(hash[:])[:12]
}

func severityRank(r RiskLevel) int {
	switch r {
	case RiskCritical:
		return 5
	case RiskHigh:
		return 4
	case RiskMedium:
		return 3
	case RiskLow:
		return 2
	default:
		return 1
	}
}

func adapters() []adapterSpec {
	return []adapterSpec{
		{
			Name:        "Codex",
			Description: "OpenAI Codex CLI and desktop agent state.",
			Paths: []pathSpec{
				portable("Codex", "~/.codex/config.toml", "Codex preferences and MCP server definitions.", true),
				portable("Codex", "~/.codex/AGENTS.md", "Global Codex instruction file.", false),
				portableDir("Codex", "~/.codex/skills", "User skill directories. Runtime-managed hidden directories should stay excluded."),
				machineLocal("Codex", "~/.codex/automations", "Local automation schedules and state should be reviewed before syncing."),
				secret("Codex", "~/.codex/auth.json", "Codex authentication material must never be copied to dotfiles."),
				runtime("Codex", "~/.codex/cache", "Runtime cache is generated by Codex."),
				runtime("Codex", "~/.codex/sessions", "Conversation/session state is runtime data."),
				appOwned("Codex", "~/.codex/sqlite", "Local application database is app-owned state."),
			},
		},
		{
			Name:        "Claude",
			Description: "Claude Code and Claude Desktop configuration.",
			Paths: []pathSpec{
				machineLocalMCP("Claude", "~/.claude.json", "Claude Code global state often mixes settings, projects, and local paths."),
				portable("Claude", "~/.claude/settings.json", "Claude Code settings are potentially portable after review.", false),
				portableDir("Claude", "~/.claude/commands", "Claude Code custom commands are usually portable."),
				portableDir("Claude", "~/.claude/agents", "Claude Code agents are usually portable."),
				appOwned("Claude", "~/.claude/projects", "Project conversation state is app-owned runtime data."),
				secret("Claude", "~/.claude/.credentials.json", "Claude credentials must never be copied to dotfiles."),
				machineLocalMCP("Claude", "~/Library/Application Support/Claude/claude_desktop_config.json", "Claude Desktop MCP config can contain local commands, paths, and env references."),
				appOwned("Claude", "~/Library/Application Support/Claude/Code Cache", "Electron cache is generated runtime state."),
			},
		},
		{
			Name:        "Cursor",
			Description: "Cursor editor settings, rules, projects, and MCP state.",
			Paths: []pathSpec{
				portable("Cursor", "~/.cursor/mcp.json", "Cursor MCP config should be reviewed before syncing.", true),
				portableDir("Cursor", "~/.cursor/rules", "Cursor rules are usually portable project/editor guidance."),
				portableDir("Cursor", "~/.cursor/skills-cursor", "Cursor skills are usually portable after review."),
				appOwned("Cursor", "~/.cursor/projects", "Cursor project databases are app-owned state."),
				appOwned("Cursor", "~/.cursor/extensions", "Installed extension binaries are app-owned; export IDs instead."),
				appOwned("Cursor", "~/.cursor/ai-tracking", "AI usage tracking databases are app-owned local data."),
				portable("Cursor", "~/Library/Application Support/Cursor/User/settings.json", "Cursor user settings are potentially portable.", false),
				portable("Cursor", "~/Library/Application Support/Cursor/User/keybindings.json", "Cursor keybindings are portable editor settings.", false),
				portable("Cursor", "~/Library/Application Support/Cursor/User/mcp.json", "Cursor user MCP config should be reviewed before syncing.", true),
			},
		},
		{
			Name:        "Windsurf",
			Description: "Windsurf editor settings and MCP state.",
			Paths: []pathSpec{
				portable("Windsurf", "~/.windsurf/mcp.json", "Windsurf MCP config should be reviewed before syncing.", true),
				portableDir("Windsurf", "~/.windsurf/rules", "Windsurf rules are usually portable guidance."),
				portable("Windsurf", "~/Library/Application Support/Windsurf/User/settings.json", "Windsurf user settings are potentially portable.", false),
				portable("Windsurf", "~/Library/Application Support/Windsurf/User/keybindings.json", "Windsurf keybindings are portable editor settings.", false),
				portable("Windsurf", "~/Library/Application Support/Windsurf/User/mcp.json", "Windsurf user MCP config should be reviewed before syncing.", true),
			},
		},
		{
			Name:        "VS Code",
			Description: "VS Code settings, extension exports, and MCP state.",
			Paths: []pathSpec{
				portable("VS Code", "~/.vscode/vscode-extensions", "Plain extension ID export is portable.", false),
				appOwned("VS Code", "~/.vscode/extensions", "Installed extension binaries are app-owned; export IDs instead."),
				portable("VS Code", "~/Library/Application Support/Code/User/settings.json", "VS Code user settings are potentially portable.", false),
				portable("VS Code", "~/Library/Application Support/Code/User/keybindings.json", "VS Code keybindings are portable editor settings.", false),
				portable("VS Code", "~/Library/Application Support/Code/User/mcp.json", "VS Code MCP config should be reviewed before syncing.", true),
				portableDir("VS Code", "~/Library/Application Support/Code/User/snippets", "VS Code snippets are usually portable."),
			},
		},
		{
			Name:        "Raycast",
			Description: "Raycast extension and local app state.",
			Paths: []pathSpec{
				machineLocal("Raycast", "~/.config/raycast", "Raycast config may be portable, but extension preferences can include local paths."),
				appOwned("Raycast", "~/Library/Application Support/com.raycast.macos", "Raycast encrypted databases and runtime state are app-owned."),
				appOwned("Raycast", "~/Library/Application Support/com.raycast.shared", "Shared Raycast runtime state is app-owned."),
			},
		},
		{
			Name:        "Generic MCP",
			Description: "Common standalone MCP config files.",
			Paths: []pathSpec{
				portable("Generic MCP", "~/.mcp.json", "Standalone MCP config should be reviewed before syncing.", true),
				portable("Generic MCP", "~/.config/mcp/mcp.json", "Standalone MCP config should be reviewed before syncing.", true),
			},
		},
	}
}

func portable(tool, rel, reason string, mcp bool) pathSpec {
	return pathSpec{Tool: tool, RelPath: rel, Classification: Portable, Risk: RiskLow, Reason: reason, Recommendation: "Review and sync through a private dotfiles repo if paths are portable.", CheckMCP: mcp}
}

func portableDir(tool, rel, reason string) pathSpec {
	spec := portable(tool, rel, reason, false)
	spec.KindHint = "directory"
	return spec
}

func machineLocal(tool, rel, reason string) pathSpec {
	return pathSpec{Tool: tool, RelPath: rel, Classification: MachineLocal, Risk: RiskMedium, Reason: reason, Recommendation: "Keep local-only unless reviewed and templated for portability."}
}

func machineLocalMCP(tool, rel, reason string) pathSpec {
	spec := machineLocal(tool, rel, reason)
	spec.CheckMCP = true
	return spec
}

func secret(tool, rel, reason string) pathSpec {
	return pathSpec{Tool: tool, RelPath: rel, Classification: SecretAuth, Risk: RiskCritical, Reason: reason, Recommendation: "Exclude from backups and store credentials in a password manager or secret store."}
}

func runtime(tool, rel, reason string) pathSpec {
	return pathSpec{Tool: tool, RelPath: rel, Classification: RuntimeCache, Risk: RiskInfo, Reason: reason, Recommendation: "Exclude; this is generated runtime state."}
}

func appOwned(tool, rel, reason string) pathSpec {
	return pathSpec{Tool: tool, RelPath: rel, Classification: AppOwned, Risk: RiskHigh, Reason: reason, Recommendation: "Exclude unless the app documents a safe export format."}
}

func findingID(rule, tool, path, evidence string) string {
	return fmt.Sprintf("%s-%s", rule, stableID(tool, path, evidence))
}
